branches:
  only:
    - master

nuget:
  account_feed: true
  project_feed: true

configuration:
  - Release

install:
  - build/appveyor/to_install.bat

before_build:
  - build/appveyor/to_before_build.bat

build:
  project: out/msbuild/demo.sln
  publish_nuget: true

after_build:
  - build/appveyor/to_after_build.bat

artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: B01jYPuw/La7q7mGSHCiTteUfYzZdle01244QZFjCa+gPAePtzEKt7Wdm0jjpeNz
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      configuration: Release
      appveyor_repo_tag: true

  - provider: NuGet
    server: https://ci.appveyor.com/nuget/alexchicn-csflj3bn8kch
    api_key:
      secure: tzXr5wKUBQBiLGbyMl03+U44PNwnTZb1/sivSw52H1U=
    skip_symbols: true
    symbol_server: https://your.symbol.server/feed
    artifact: /.*\.nupkg/
    on:
      configuration: Release

