name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -D USE_COVERALLS=TRUE ../build/cmake
        make
