name: 'release'

on:
  push:
    paths-ignore:
    - '.github/**'
    - 'docs/**'
    - 'README.md'
    - 'LICENSE'
    - '.readthedocs.yml'
    - '.git*'
    tags:
    - '*'

jobs:
  release:
    name: 'release'
    runs-on: ubuntu-latest
    steps:
    - name: 'checkout'
      uses: actions/checkout@v2
    - name: 'release'
      run: echo release
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ../
        make
        cd ../
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test.linux
        path: output/
    - name: 'deploy to release'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: '${{ github.ref }}'
        release_name: 'Release v${{ github.ref }}'
        body: |
          changes in this release
          - A
          - B
        draft: false
        prerelease: false
