name: ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -D ../
        make
        cd ..
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test
        path: output/
