name: ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir out
        cd out
        mkdir make
        cd make
        cmake -D USE_COVERALLS=TRUE ../../build/cmake
        make
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test
        path: out/
