name: CI-windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir out
        cd out
        mkdir make
        cd make
        cmake -G "Visual Studio 16 2019" -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_CXX_COMPILER_ID=MSVC ../../build/cmake
